Adds detection for stale PID files to the start and docker script.

diff --git a/structr-ui/src/main/resources/bin/start b/structr-ui/src/main/resources/bin/start
--- a/structr-ui/src/main/resources/bin/start
+++ b/structr-ui/src/main/resources/bin/start
@@ -7,15 +7,28 @@ cd $BASE_DIR/..
 
 if [ -e $PID_FILE ]; then
 
-	echo
-	echo "        ERROR: server already running."
-	echo
-	echo "        Please stop any running instances before starting a"
-	echo "        new one. (Remove $PID_FILE if this message appears"
-	echo "        even if no server is running.)"
-	echo
+	$(ps aux | grep "org.structr.Server" | grep -v grep > /dev/null)
 
-	exit 0
+	result=$?
+
+	if [ $result -eq 1 ]; then
+		echo 
+		echo "        Found $PID_FILE, but server is not running."
+		echo "        Removing $PID_FILE and proceeding with startup."
+		echo
+
+		rm $PID_FILE
+	else
+		echo
+		echo "        ERROR: server already running."
+		echo
+		echo "        Please stop any running instances before starting a"
+		echo "        new one. (Remove $PID_FILE if this message appears"
+		echo "        even if no server is running.)"
+		echo
+
+		exit 0
+	fi
 
 fi
 
